config/routes.rb
Rails.application.routes.draw do

  get "auth/:provider/callback", to: "sessions#create"
  get "signin", to: "sessions#new", as: "signin"

  root "sessions#new"

  resources :auth, only: :show
  resources :sessions, only: [:destroy, :new]
  resources :shirts
  resources :users

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/shirt.rb
class Shirt < ApplicationRecord
  attr_accessor :last_worn_today
  belongs_to :user

  mount_uploader :picture, PictureUploader
  validates_presence_of :name
end

app/models/user.rb
class User < ApplicationRecord
  has_many :shirts

  validates_format_of :name, with: /\A[\w-]+\z/, message: "May only contain letters, numbers, dashes, and underscores."
  validates_presence_of :email, :name, :oauth_uid
  validates_uniqueness_of :oauth_uid, :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :user_signed_in?
  protect_from_forgery with: :exception

  def authenticate_user!
    if !user_signed_in?
      flash[:warning] = "You need to sign in before continuing."
      redirect_to new_session_path
    end
  end

  def authorize_object_owner(object)
    unless object.user == current_user
      flash[:warning] = "You are not authorized to view this record."
      redirect_to shirts_path
    end
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def user_signed_in?
    !current_user.nil?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.find_by(oauth_uid: request.env["omniauth.auth"]["uid"])
    if user.nil?
      session[:auth] = request.env["omniauth.auth"].slice("uid","info")
      redirect_to new_user_path
    else
      user.increment! :sign_in_count
      user.touch :last_signed_in_at
      session[:user_id] = user.id
      redirect_to shirts_path
    end
  end

  def destroy
    session[:user_id] = nil
    session[:auth] = nil
    flash[:success] = "Signed out."
    redirect_to root_path
  end

  def new
    redirect_to shirts_path if user_signed_in?
  end

end

app/controllers/shirts_controller.rb
class ShirtsController < ApplicationController

  before_action :authenticate_user!

  def create
    @shirt = Shirt.new(shirt_params)
    @shirt.user = current_user
    if @shirt.save
      @shirt.touch(:last_worn_at) if params[:shirt][:last_worn_today] == "1"
      flash[:success] = "Shirt created."
      redirect_to @shirt
    else
      flash[:alert] = "There was a problem creating this shirt."
      render :new
    end
  end

  def destroy
    @shirt = Shirt.find(params[:id])
    authorize_object_owner(@shirt)
    if @shirt.destroy
      flash[:success] = "Shirt deleted."
      redirect_to shirts_path
    else
      flash[:alert] = "There was a problem deleting this shirt."
      render :show
    end
  end

  def edit
    @shirt = Shirt.find(params[:id])
    authorize_object_owner(@shirt)
  end

  def index
    @shirts = current_user.shirts.order(:name)
  end

  def new
    @shirt = Shirt.new
  end

  def show
    @shirt = Shirt.find(params[:id])
    authorize_object_owner(@shirt)
  end

  def update
    @shirt = Shirt.find(params[:id])
    authorize_object_owner(@shirt)
    if @shirt.update(shirt_params)
      @shirt.touch(:last_worn_at) if params[:shirt][:last_worn_today] == "1"
      flash[:success] = "Shirt updated."
      redirect_to @shirt
    else
      flash[:alert] = "There was a problem updating this shirt."
      render :edit
    end
  end

  protected

  def shirt_params
    params.require(:shirt).permit(:description, :name, :picture)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def create
    @user = User.new(user_params)
    @user.email = session[:auth]["info"]["email"]
    @user.oauth_uid = session[:auth]["uid"]
    if @user.save
      session[:auth].clear
      session[:user_id] = @user.id
      @user.touch :last_signed_in_at
      @user.increment! :sign_in_count
      flash[:success] = "Registered successfully."
      redirect_to shirts_path
    else
      flash[:alert] = "There was a problem registering."
      render :new
    end
  end

  def new
    @user = User.new(oauth_uid: session[:auth]["uid"])
  end

  def show
    @user = User.find(params[:id])
    unless @user == current_user
      flash[:warning] = "You are not authorized to view this record."
      redirect_to shirts_path
    end
  end

  protected

  def user_params
    params.require(:user).permit(:name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!! 5
%html{ :lang => "en" }
  %head
    %meta{ :charset => "utf-8" }

    %meta{ :name => "viewport", :content => "width=device-width, initial-scale=1.0" }

    %title= content_for?(:title) ? yield(:title) : "Shirts"

    %link{href: "https://fonts.googleapis.com/css?family=Abril+Fatface", rel: "stylesheet"}/
    %link{href: "https://fonts.googleapis.com/css?family=Roboto", rel: "stylesheet"}/
    = stylesheet_link_tag "application"
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tag

  %body
    .top-bar
      .top-bar-left
        %ul.menu
          %li.header-style.menu-text
            =link_to "Shirts", shirts_path
          -if user_signed_in?
            %li.menu-text Signed in as:
            %li
              =link_to current_user.name, current_user
          -else
            %li.menu-text
              Not signed in.
      -if user_signed_in?
        .top-bar-right
          %ul.menu
            %li.sign-out
              =link_to "Sign Out", session_path(:current), method: :delete
    -flash.each do |name, msg|
      %div{ class: name + " callout", data: { closable: "" }}
        = content_tag :span, msg
        %button.close-button{"aria-label" => "Dismiss alert", data: { close: "" }, type: "button"}
          %span{"aria-hidden" => "true"} &times;
    = yield

app/views/shirts/_form.html.haml
.row
  .small-12.medium-5.small-centered.columns
    =simple_form_for @shirt do |f|
      =f.input :name, label: false, placeholder: "Name"
      =f.file_field :picture
      =f.input :description, input_html: { style: "height: 8rem;" }, label: false, placeholder: "Description"
      .row
        .small-1.column
          =f.input :last_worn_today, as: :boolean, label: false
        .small-11.columns
          =f.label "Wearing today?"
      =f.button :submit

app/views/shirts/edit.html.haml
.row
  .small-12.columns
    %h1.text-center
      Edit
      =@shirt.name
    %nav{"aria-label" => "You are here:", :role => "navigation"}
      %ul.breadcrumbs.callout
        %li
          =link_to "Shirts", shirts_path
        %li
          =link_to @shirt.name, @shirt
        %li
          %span.show-for-sr Current:
          Edit
    = render "form"

app/views/shirts/index.html.haml
.row
  .small-12.columns
    %h1.text-center Shirts
    .row
      .small-12.medium-5.small-centered.columns
        .callout
          %p
            =link_to "New", new_shirt_path, class: "button float-right"
          %ul
            -@shirts.each do |shirt|
              %li= link_to shirt.name, shirt

app/views/shirts/new.html.haml
.row
  .small-12.columns
    %h1.text-center New Shirt
    %nav{"aria-label" => "You are here:", :role => "navigation"}
      %ul.breadcrumbs.callout
        %li
          =link_to "Shirts", shirts_path
        %li
          %span.show-for-sr Current:
          New Shirt
    = render "form"

app/views/shirts/show.html.haml
.row
  .small-12.columns
    %h1.text-center
      =@shirt.name
      =link_to @shirt, class: "float-right", data: { confirm: "Are you sure?" }, method: :delete do
        =fa_icon "trash-o"
    %nav{"aria-label" => "You are here:", :role => "navigation"}
      %ul.breadcrumbs.callout
        %li
          =link_to "Shirts", shirts_path
        %li
          %span.show-for-sr Current:
          =@shirt.name
    .row
      .small-12.medium-5.small-centered.columns
        .callout
          %h3
            =link_to edit_shirt_path(@shirt), class: "float-right", id: "edit_shirt" do
              =fa_icon "pencil-square-o"
          -if @shirt.last_worn_at.present?
            %p
              %strong Last Worn:
              =distance_of_time_in_words_to_now(@shirt.last_worn_at)
              ago
          -unless @shirt.picture.blank?
            =image_tag @shirt.picture.url, alt: "#{@shirt.name}: #{@shirt.description}", class: "thumbnail"
          -unless @shirt.description.empty?
            %p= @shirt.description

app/views/users/new.html.haml
.row
  .small-12.columns
    %h1.text-center Register
    .row
      .small-12.medium-5.small-centered.columns
        =simple_form_for @user do |f|
          =f.input :name, label: false, placeholder: "UserName"
          =f.button :submit

app/views/users/show.html.haml
.row
  .small-12.medium-5.small-centered.columns
    .callout
      %h1.text-center
        =fa_icon "user"
        =@user.name
      %p
        %strong Member Since:
        =distance_of_time_in_words_to_now(@user.created_at)
        ago
      %p
        %strong Sign In Count:
        =@user.sign_in_count
      %p
        %strong Last Sign In:
        =distance_of_time_in_words_to_now(@user.last_signed_in_at)
        ago